New log file opened at Mon Jan 16 17:27:18 CET 2017 by 3416@Besitzer-PC
Taking next connection to: 55948
New client attempting to connect on port: 55951-55948
  Address = /192.168.0.102:55948
This client on port 55951 has uuid 9713cfe7-c100-4410-9f24-619b2f228946 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-9713cfe7-c100-4410-9f24-619b2f228946
Taking next connection to: 55948
New client attempting to connect on port: 55953-55948
  Address = /192.168.0.102:55948
Handshake exception on socket: 55953
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 55948
New client attempting to connect on port: 55954-55948
  Address = /192.168.0.102:55948
This client on port 55954 has uuid 671d6285-3be4-458f-8aad-5b59729b45c9 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-9713cfe7-c100-4410-9f24-619b2f228946, activator-671d6285-3be4-458f-8aad-5b59729b45c9
Taking next connection to: 55948
New client attempting to connect on port: 55975-55948
  Address = /192.168.0.102:55948
Handshake exception on socket: 55975
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 55948
New client attempting to connect on port: 55976-55948
  Address = /192.168.0.102:55948
This client on port 55976 has uuid a1af1c1e-6677-49b6-99d7-80e7371716af configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-671d6285-3be4-458f-8aad-5b59729b45c9, play-fork-run-a1af1c1e-6677-49b6-99d7-80e7371716af
Taking next connection to: 55948
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 55948
